/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_applications_multi_project.app;

import java_applications_multi_project.list.LinkedList;

import static java_applications_multi_project.utilities.StringUtils.join;
import static java_applications_multi_project.utilities.StringUtils.split;
import static java_applications_multi_project.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
